### ISSUE TITLE
Berkshelf 3.x Integration

### ISSUE THREAD

**Issue by ehaselwanter** [jonlives/knife-spork#109]
```
cat Gemfile
source 'https://rubygems.org'

# get Berkshelf 3.0.beta

gem 'chef'
gem "berkshelf", github: "berkshelf/berkshelf"
gem 'knife-spork'

$ grep -e berkshelf -e knife-spork Gemfile.lock
  remote: git://github.com/berkshelf/berkshelf.git
    berkshelf (3.0.0.beta6)
      berkshelf-api-client (~> 1.1)
    berkshelf-api-client (1.1.1)
    knife-spork (1.3.2)
  berkshelf!
  knife-spork

```
- does not work out of the box at all (must do a require 'berkshelf' in the runner.rb)
- lockfile should be lockfile = ::Berkshelf::Lockfile.from_berksfile(berksfile)
- load_from_berkshelf(name) is broken with berkshelf 3.x

```
knife spork upload base
ERROR: Berkshelf::BerkshelfError: LockFileNotFound

knife spork check base -VV
DEBUG: No chefignore file found at /Users/ehaselwanter/chef-repo-homenetwork/cookbooks/chefignore no files will be ignored
/Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/bundler/gems/berkshelf-eb7fc61e861e/lib/berkshelf/berksfile.rb:18:in `exist?': can't convert nil into String (TypeError)
    from /Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/bundler/gems/berkshelf-eb7fc61e861e/lib/berkshelf/berksfile.rb:18:in `from_file'
    from /Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/gems/knife-spork-1.3.2/lib/knife-spork/runner.rb:147:in `load_from_berkshelf'
    from /Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/gems/knife-spork-1.3.2/lib/knife-spork/runner.rb:132:in `load_cookbook'
    from /Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/gems/knife-spork-1.3.2/lib/chef/knife/spork-check.rb:108:in `initial_load'
    from /Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/gems/knife-spork-1.3.2/lib/chef/knife/spork-check.rb:49:in `run'
    from /Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/gems/chef-11.10.2/lib/chef/knife.rb:491:in `run_with_pretty_exceptions'
    from /Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/gems/chef-11.10.2/lib/chef/knife.rb:174:in `run'
    from /Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/gems/chef-11.10.2/lib/chef/application/knife.rb:135:in `run'
    from /Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/gems/chef-11.10.2/bin/knife:25:in `<top (required)>'
    from /Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/bin/knife:23:in `load'
    from /Users/ehaselwanter/.rvm/gems/ruby-1.9.3-p484@cookbooks/bin/knife:23:in `<main>'
```

is there anybody working on this. or does nobody use berkshelf with spork.

I can do a 

```
berks vendor
knife spork check base -o berks-cookbooks
```

but this is not what I want to do, and I get 

```
WARNING: Your local version (0.2.2) is frozen on the remote server. You'll need to bump before you can upload.
Would you like to perform a patch-level bump on the base cookbook now? (Y/N)
```

with this

**Comment by grampajoe** [comment]
This is still an issue in 1.6.0, and masks problems in the `load_from_chef` method.

The specific issue I had was not having my `cookbook_path` set correctly, but seeing the `LockFileNotFound` error without any messages about not finding the cookbook locally. It took a while to realize it was falling through `load_from_chef` for me, but not for coworkers, and that the problem wasn't actually (or only) with Berkshelf.

Maybe it'd help to add feedback in `load_from_{chef,berkshelf,librarian}` to tell us which methods are failing?
