### ISSUE TITLE
uninitialized constant KnifeSpork::Runner::InstanceMethods::Yajl (NameError)

### ISSUE THREAD

**Issue by mrjcleaver** [jonlives/knife-spork#170]
Hi Jon,

Any clues?

````
martincleaver@martincleaversmbp:~/SoftwareDevelopment/Chef/bp_linux_checks/templates/default 13:17:21 554$ knife spork environment check test_wheezy -VV
/Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.4.2/lib/knife-spork/runner.rb:234:in `rescue in load_environment_from_file': uninitialized constant KnifeSpork::Runner::InstanceMethods::Yajl (NameError)
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.4.2/lib/knife-spork/runner.rb:232:in `load_environment_from_file'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.4.2/lib/knife-spork/runner.rb:37:in `block in run_plugins'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.4.2/lib/knife-spork/runner.rb:37:in `collect'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.4.2/lib/knife-spork/runner.rb:37:in `run_plugins'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.4.2/lib/chef/knife/spork-environment-check.rb:25:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:34:in `load'
	from /opt/chefdk/bin/knife:34:in `<main>'
martincleaver@martincleaversmbp:~/SoftwareDevelopment/Chef/bp_linux_checks/templates/default 13:18:23 555$ knife spork info
Config Hash:
{"default_environments"=>["test_wheezy"], "version_change_threshold"=>2}

Plugins:
KnifeSpork::Plugins::Campfire: disabled
KnifeSpork::Plugins::Eventinator: disabled
KnifeSpork::Plugins::Foodcritic: disabled
KnifeSpork::Plugins::Git: disabled
KnifeSpork::Plugins::Graphite: disabled
KnifeSpork::Plugins::Grove: disabled
KnifeSpork::Plugins::HipChat: disabled
KnifeSpork::Plugins::Irccat: disabled
KnifeSpork::Plugins::Jabber: disabled
KnifeSpork::Plugins::Rubocop: disabled
KnifeSpork::Plugins::Slack: disabled
KnifeSpork::Plugins::StatusNet: disabled
````

Thanks, Martin.

**Comment by jonlives** [comment]
@mrjcleaver I think this might be the same issue as https://github.com/jonlives/knife-spork/pull/165 fixed -  it'll be included in the next release :)

**Comment by mrjcleaver** [comment]
Thanks for the reference. I patched my gem.

For the record I was also getting:
````
ERROR: Psych::SyntaxError: (/Volumes/Storage/martincleaver/.chef/spork-config.yml): did not find expected key while parsing a block mapping at line 1 column 1
````

Via https://www.ruby-forum.com/topic/4411986 I found this was invalid YAML, validated with http://www.yamllint.com

**Comment by mrjcleaver** [comment]
Re: 1.5.0.beta2 - https://github.com/jonlives/knife-spork/pull/165#issuecomment-71440121 - thanks @jonlives: I installed via specific_gem and re-ran my test.
````
  508  20150126-09:57:57  gem install specific_install
  510  20150126-09:58:52  gem specific_install https://github.com/jonlives/knife-spork/releases/download/1.5.0.beta2/knife-spork-1.5.0.beta2.gem
  520  20150126-10:06:13  knife spork environment check test_wheezy -VV
````

I no longer get the error as before - I get the same as after I'd patched. 
````
martincleaver@martincaversmbp:~/SoftwareDevelopment/Chef/bp_linux_checks/templates/default 10:09:03 524$ knife spork environment check test_wheezy -VV
/opt/chefdk/embedded/apps/chef/lib/chef/knife/core/object_loader.rb:88:in `read': No such file or directory @ rb_sysopen - ~/.spork/environments/test_wheezy.json (Errno::ENOENT)
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/object_loader.rb:88:in `object_from_file'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.5.0.beta2/lib/knife-spork/runner.rb:235:in `load_environment_from_file'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.5.0.beta2/lib/knife-spork/runner.rb:39:in `block in run_plugins'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.5.0.beta2/lib/knife-spork/runner.rb:39:in `collect'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.5.0.beta2/lib/knife-spork/runner.rb:39:in `run_plugins'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.5.0.beta2/lib/chef/knife/spork-environment-check.rb:25:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:34:in `load'
	from /opt/chefdk/bin/knife:34:in `<main>'
````

Of course it's a different issue as to needing that environments file, but I can confirm that beta2 has eliminated the spurious error.

**Comment by jonlives** [comment]
@mrjcleaver fantastic, thanks for testing that for me :) The fix'll be in the next release.
