### ISSUE TITLE
No such file or directory @ rb_sysopen .../environments/foo.json

### ISSUE THREAD

**Issue by mrjcleaver** [jonlives/knife-spork#172]
Forgive my silly question but...

Why might:
````
 knife spork environment create foo; 
 knife spork environment check foo
````
 then complain that 
````
ERROR: Errno::ENOENT: No such file or directory @ rb_sysopen - /Volumes/Storage/martincleaver/SoftwareDevelopment/Chef/environments/foo.json
````

Surely whatever it wanted would have been made as part of create?

And, I'm clearly missing something because I get the same error when checking environments that do already exist in production.

I don't use Berkshelf if that gives a clue. (Am using skip_berkshelf)

**Comment by jonlives** [comment]
That's happening because knife spork environment create doesn't actually create the local file, just creates the env on the server. Should be easy enough to add an option for it to do this though.

**Comment by jonlives** [comment]
This is fixed and out in 1.5.0 :) I added the save_environment_locally_on_create config flag to enable this behaviour.

**Comment by mrjcleaver** [comment]
Hi Jon. Ok. just tested:
```
martincleaver@martincaversmbp:~/SoftwareDevelopment/Chef/bp_linux_checks/templates/default 16:34:08 513$  knife spork environment create foo
Created foo
Saving environment changes to foo.json
martincleaver@martincaversmbp:~/SoftwareDevelopment/Chef/bp_linux_checks/templates/default 16:34:22 514$  knife spork environment check foo -VV
/opt/chefdk/embedded/apps/chef/lib/chef/knife/core/object_loader.rb:88:in `read': No such file or directory @ rb_sysopen - ~/.spork/environments/foo.json (Errno::ENOENT)
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/object_loader.rb:88:in `object_from_file'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.5.0/lib/knife-spork/runner.rb:248:in `load_environment_from_file'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.5.0/lib/knife-spork/runner.rb:39:in `block in run_plugins'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.5.0/lib/knife-spork/runner.rb:39:in `collect'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.5.0/lib/knife-spork/runner.rb:39:in `run_plugins'
	from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.5.0/lib/chef/knife/spork-environment-check.rb:25:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:34:in `load'
	from /opt/chefdk/bin/knife:34:in `<main>'
martincleaver@martincaversmbp:~/SoftwareDevelopment/Chef/bp_linux_checks/templates/default 16:34:28 515$ grep save_environment_locally_on_create ~/.chef/spork-config.yml
save_environment_locally_on_create: true
````

Should this have worked?

**Comment by jonlives** [comment]
@mrjcleaver could you please gist the cookbook_path you're using in your knife.rb and also whether you're using the environment_path option in your spork-config.yml?

Essentially, spork will save the environment to your environment_path if specified, and if not will save it to your cookbook_path (substituting /cookbooks for /environments). It may be your cookbook path naming isn't hitting those patterns, if so it might be worth setting environment_path

**Comment by mrjcleaver** [comment]
Ok, so: https://gist.github.com/mrjcleaver/749e0386994c7824692b

From what you say I think it should be saving to ~/.spork/enviroments/<env-name>

Thx, M.

**Comment by mrjcleaver** [comment]
Just for giggles:

````
martincleaver@martincaversmbp:~/.spork/environments 14:34:01 609$ knife environment show -fj development > development.json
martincleaver@martincaversmbp:~/.spork/environments 14:34:17 610$ cd -
/Volumes/Storage/martincleaver/SoftwareDevelopment/Chef/bp_elkstack
martincleaver@martincaversmbp:~/SoftwareDevelopment/Chef/bp_elkstack 14:34:21 611$ knife spork omni bp_elkstack
WARNING: Unloading Berkshelf as skip_berkshelf option found in config
OMNI: Bumping bp_elkstack
WARNING: Unloading Berkshelf as skip_berkshelf option found in config
Successfully bumped bp_elkstack to v0.1.17!

OMNI: Uploading bp_elkstack
WARNING: Unloading Berkshelf as skip_berkshelf option found in config
Freezing bp_elkstack at 0.1.17...
Successfully uploaded bp_elkstack@0.1.17!

OMNI: Promoting bp_elkstack
WARNING: Unloading Berkshelf as skip_berkshelf option found in config
ERROR: Errno::ENOENT: No such file or directory @ rb_sysopen - ~/.spork/environments/development.json
martincleaver@martincaversmbp:~/SoftwareDevelopment/Chef/bp_elkstack 14:34:37 612$ ls -la ~/.spork/environments/development.json
-rw-r--r--  1 martincleaver  staff  1833  5 Feb 14:34 /Volumes/Storage/martincleaver/.spork/environments/development.json
````

Maybe it doesn't expand ~ ?

**Comment by mrjcleaver** [comment]
Yup.

````
martincleaver@martincaversmbp:~/SoftwareDevelopment/Chef/bp_elkstack 14:34:49 613$ emacs ~/.chef/spork-config.yml   ## /Volumes/..../ instead of ~
martincleaver@martincaversmbp:~/SoftwareDevelopment/Chef/bp_elkstack 14:36:22 614$ knife spork omni bp_elkstack
WARNING: Unloading Berkshelf as skip_berkshelf option found in config
OMNI: Bumping bp_elkstack
WARNING: Unloading Berkshelf as skip_berkshelf option found in config
Successfully bumped bp_elkstack to v0.1.18!

OMNI: Uploading bp_elkstack
WARNING: Unloading Berkshelf as skip_berkshelf option found in config
Freezing bp_elkstack at 0.1.18...
Successfully uploaded bp_elkstack@0.1.18!

OMNI: Promoting bp_elkstack
WARNING: Unloading Berkshelf as skip_berkshelf option found in config
ERROR: Errno::ENOENT: No such file or directory @ rb_sysopen - /Volumes/Storage/martincleaver/.spork/environments//test_wheezy.json
martincleaver@martincaversmbp:~/SoftwareDevelopment/Chef/bp_elkstack 14:36:33 
````

But then that leads me to the question of how is this environments folder maintained? Do I have to copy changes using knife environment show x -fj to keep it up to date? Surely it should go fetch from the server?
