### ISSUE TITLE
Improvement: bump this cookbook

### ISSUE THREAD

**Issue by alexpop** [jonlives/knife-spork#186]
I often find myself in the root of a cookbook making changes, kitchen converging, committing to version control, etc.

Would be helpful to have a way to bump the version of the cookbook I'm in. For example, run:
```bash
knife spork bump
```

I'm currently using this alias to accomplish the same thing:

```bash
[05:17:38 ~/cookbooks/mytest {master}]$ alias bump='knife spork bump ${PWD##*/} -o ..'
[05:17:52 ~/cookbooks/mytest {master}]$ bump
Successfully bumped mytest to v0.1.1!
[05:17:54 ~/cookbooks/mytest {master}]$ bump
Successfully bumped mytest to v0.1.2!
[05:17:57 ~/cookbooks/mytest {master}]$ bump minor
Successfully bumped mytest to v0.2.2!
```

**Comment by alexpop** [comment]
The Powershell equivalent alias in Windows:

```powershell
PS C:\Users\apop\mytest> function bump { knife spork bump $(split-path (get-location) -leaf) -o .. }
PS C:\Users\apop\mytest> bump
Successfully bumped mytest to v0.1.3!
```

**Comment by dpnl87** [comment]
Nice one @alexpop! For now I'll use your alias to do the same ting :smiley:

**Comment by jonlives** [comment]
Nice, I like this idea - added to the milestone for the next release!

**Comment by jonlives** [comment]
Released in 1.6.0

**Comment by alexpop** [comment]
Hey Jon, thanks for working on this.

I tried to use it, but here's the exception I'm getting:

```bash
[12:16:01 ~/git/push-jobs {alexpop/idempotent_windows_package}]$ chef -v
Chef Development Kit Version: 0.7.0
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.2

[12:16:08 ~/git/push-jobs {alexpop/idempotent_windows_package}]$ chef gem install knife-spork
Successfully installed knife-spork-1.6.0
1 gem installed

[12:16:16 ~/git/push-jobs {alexpop/idempotent_windows_package}]$ knife spork bump -VV
WARNING: No knife configuration file found
Cookbook name omitted, but metadata.rb for cookbook 'push-jobs' found - bumping that.
/Users/apop/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.6.0/lib/knife-spork/runner.rb:181:in `load_cookbook': Could not find cookbook ''push-jobs'' in any of the sources! (Chef::Exceptions::CookbookNotFound)
	from /Users/apop/.chefdk/gem/ruby/2.1.0/gems/knife-spork-1.6.0/lib/chef/knife/spork-bump.rb:56:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:425:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:424:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:215:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:55:in `load'
	from /opt/chefdk/bin/knife:55:in `<main>'
```

**Comment by jonlives** [comment]
@alexpop knife-spork expects to be able to find the cookbook you're working on under a configured cookbook_path in knife.rb - it's just extracting the name from the metadata.rb file in current dir instead of from the command line arg.  Refactoring it to not use the cookbook_paths at all would be a pretty big job.

**Comment by alexpop** [comment]
I  understand. Could you add the parent directory to `cookbook_paths` when the cookbook name is extracted from metadata.rb?

The alias(`knife spork bump ${PWD##*/} -o ..`) I'm currently using is doing that and I haven't seen any side effects so far.

**Comment by jonlives** [comment]
@alexpop Out of curiosity, does your manual alias work on the ```idempotent_windows_package``` example you gave above? I'd have suspected that would fail too if it wasn't found in a cookbook_path

**Comment by alexpop** [comment]
Yes, my original alias is still working, here's the output:

```bash
[01:16:00 ~/git/push-jobs {alexpop/idempotent_windows_package}]$ knife spork bump ${PWD##*/} -o ..
WARNING: No knife configuration file found
Successfully bumped push-jobs to v2.4.2!

[01:16:28 ~/git/push-jobs {alexpop/idempotent_windows_package}]$ knife spork bump ${PWD##*/} -o ..
WARNING: No knife configuration file found
Successfully bumped push-jobs to v2.4.3!

[01:16:31 ~/git/push-jobs {alexpop/idempotent_windows_package}]$ knife spork bump ${PWD##*/} -o .. minor
WARNING: No knife configuration file found
Successfully bumped push-jobs to v2.5.0!

[01:16:36 ~/git/push-jobs {alexpop/idempotent_windows_package}]$ knife spork bump -o ..
WARNING: No knife configuration file found
Cookbook name omitted, but metadata.rb for cookbook 'push-jobs' found - bumping that.
ERROR: Chef::Exceptions::CookbookNotFound: Could not find cookbook ''push-jobs'' in any of the sources!
```

**Comment by jonlives** [comment]
@alexpop my bad there - the error was happening when the cookbook name in metadata.rb was single quoted. I've pushed 1.6.1 with this fixed, so if you install that version hopefully it should work now.

**Comment by alexpop** [comment]
Yes, 1.6.1 fixed `knife spork bump -o ..` 

```bash
[01:17:01 ~/git/push-jobs {alexpop/idempotent_windows_package}]$ chef gem install knife-spork
Fetching: knife-spork-1.6.1.gem (100%)
Successfully installed knife-spork-1.6.1
1 gem installed

[01:31:43 ~/git/push-jobs {alexpop/idempotent_windows_package}]$ knife spork bump -o ..
WARNING: No knife configuration file found
Cookbook name omitted, but metadata.rb for cookbook push-jobs found - bumping that.
Successfully bumped push-jobs to v2.5.1!
```

I've also noticed that the `major | minor |...` options are not working using this use-case:
```bash
[01:31:55 ~/git/push-jobs {alexpop/idempotent_windows_package}]$ knife spork bump -o .. minor
WARNING: No knife configuration file found
ERROR: Chef::Exceptions::CookbookNotFound: Could not find cookbook 'minor' in any of the sources!
```

It will also be great to not have to specify `-o ..`
Do you see any issues with adding `..` to `cookbook_path` when the cookbook name is not specified?

**Comment by jonlives** [comment]
@alexpop I'd definitely be willing to look at doing it :) Could I ask that you please open a new issue for that as it'll likely be a week or two before I'm able to look at it and this specific issue is resolved.

**Comment by alexpop** [comment]
Sure, will do that, thanks
