### ISSUE TITLE
omni: Bad error message when cookbook is not found

### ISSUE THREAD

**Issue by takano-akio** [jonlives/knife-spork#208]
If I run `knife spork omni` on a non-existent cookbook, I get:

```
% knife spork omni xyz
OMNI: Bumping xyz
ERROR: TypeError: no implicit conversion of nil into String
```

It would be nice if the error message mentioned the fact that `xyz` could not be found.

Here is the verbose output:

```
% knife spork omni xyz -VV
INFO: Using configuration from /home/akio/.chef/knife.rb
OMNI: Bumping xyz
DEBUG: No chefignore file found at /home/akio/src/chefignore no files will be ignored
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-spork-1.6.3/lib/knife-spork/runner.rb:195:in `exist?': no implicit conversion of nil into String (TypeError)
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-spork-1.6.3/lib/knife-spork/runner.rb:195:in `load_from_berkshelf'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-spork-1.6.3/lib/knife-spork/runner.rb:180:in `load_cookbook'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-spork-1.6.3/lib/chef/knife/spork-bump.rb:56:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-spork-1.6.3/lib/chef/knife/spork-omni.rb:77:in `bump'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-spork-1.6.3/lib/chef/knife/spork-omni.rb:105:in `omni'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/knife-spork-1.6.3/lib/chef/knife/spork-omni.rb:67:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/knife.rb:219:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/application/knife.rb:156:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/bin/knife:25:in `<top (required)>'
        from /usr/bin/knife:58:in `load'
        from /usr/bin/knife:58:in `<main>'
```

**Comment by takano-akio** [comment]
It turns out that the issue is no longer there in the latest version. Closing.
